-- Patch protocols table for MySQL
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE protocols
  ADD COLUMN IF NOT EXISTS category VARCHAR(255),
  ADD COLUMN IF NOT EXISTS difficulty_level VARCHAR(100),
  ADD COLUMN IF NOT EXISTS estimated_duration INT,
  ADD COLUMN IF NOT EXISTS materials TEXT,
  ADD COLUMN IF NOT EXISTS content TEXT,
  ADD COLUMN IF NOT EXISTS safety_notes TEXT,
  ADD COLUMN IF NOT EXISTS lab_id VARCHAR(64),
  ADD COLUMN IF NOT EXISTS privacy_level VARCHAR(100) DEFAULT 'lab',
  ADD COLUMN IF NOT EXISTS is_approved TINYINT(1) DEFAULT 1;

SET FOREIGN_KEY_CHECKS = 1;
