-- Patch users table with profile/settings fields
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
  ADD COLUMN IF NOT EXISTS department VARCHAR(255),
  ADD COLUMN IF NOT EXISTS specialization VARCHAR(255),
  ADD COLUMN IF NOT EXISTS bio TEXT,
  ADD COLUMN IF NOT EXISTS current_position VARCHAR(255),
  ADD COLUMN IF NOT EXISTS current_institution VARCHAR(255),
  ADD COLUMN IF NOT EXISTS location VARCHAR(255),
  ADD COLUMN IF NOT EXISTS timezone VARCHAR(100),
  ADD COLUMN IF NOT EXISTS profile_visibility VARCHAR(100) DEFAULT 'lab',
  ADD COLUMN IF NOT EXISTS show_email TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS show_phone TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS show_location TINYINT(1) DEFAULT 0;

SET FOREIGN_KEY_CHECKS = 1;
