-- Patch lab_members table with updated_at
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE lab_members
  ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

SET FOREIGN_KEY_CHECKS = 1;
