#!/bin/bash

# Production Environment E2E Testing Script
# This script runs tests against the production environment

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration for production
PRODUCTION_BASE_URL=${PRODUCTION_BASE_URL:-"https://your-production-domain.com"}
PRODUCTION_BACKEND_URL=${PRODUCTION_BACKEND_URL:-"https://api.your-production-domain.com"}
PRODUCTION_STATS_URL=${PRODUCTION_STATS_URL:-"https://stats.your-production-domain.com"}

REPORT_DIR="./test-results/production"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
LOG_FILE="$REPORT_DIR/test-run-$TIMESTAMP.log"

# Create report directory
mkdir -p "$REPORT_DIR"
mkdir -p "$REPORT_DIR/screenshots"
mkdir -p "$REPORT_DIR/coverage"

echo -e "${BLUE}🌐 Starting Production Environment E2E Testing${NC}"
echo -e "${BLUE}Production URL: $PRODUCTION_BASE_URL${NC}"
echo -e "${BLUE}Timestamp: $TIMESTAMP${NC}"
echo ""

# Set environment variables for production testing
export ENVIRONMENT=production
export BASE_URL="$PRODUCTION_BASE_URL"
export BACKEND_URL="$PRODUCTION_BACKEND_URL"
export STATS_SERVICE_URL="$PRODUCTION_STATS_URL"

# Function to check production service health
check_production_health() {
    echo -e "${YELLOW}🔍 Checking production services...${NC}"
    
    # Check frontend
    if curl -s "$PRODUCTION_BASE_URL" > /dev/null; then
        echo -e "${GREEN}✅ Production frontend is accessible${NC}"
    else
        echo -e "${RED}❌ Production frontend is not accessible${NC}"
        return 1
    fi
    
    # Check backend
    if curl -s "$PRODUCTION_BACKEND_URL/health" > /dev/null; then
        echo -e "${GREEN}✅ Production backend is accessible${NC}"
    else
        echo -e "${RED}❌ Production backend is not accessible${NC}"
        return 1
    fi
    
    # Check stats service
    if curl -s "$PRODUCTION_STATS_URL/health" > /dev/null; then
        echo -e "${GREEN}✅ Production stats service is accessible${NC}"
    else
        echo -e "${RED}❌ Production stats service is not accessible${NC}"
        return 1
    fi
    
    return 0
}

# Function to run production-specific tests
run_production_tests() {
    echo -e "${YELLOW}🧪 Running production-specific tests...${NC}"
    
    # API Tests with production endpoints
    echo -e "${BLUE}Testing API endpoints...${NC}"
    npm run test:api -- --config=jest.config.api.js 2>&1 | tee -a "$LOG_FILE"
    
    # UI Tests with production frontend
    echo -e "${BLUE}Testing UI functionality...${NC}"
    npm run test:ui -- --config=jest.config.ui.js 2>&1 | tee -a "$LOG_FILE"
    
    # Integration Tests
    echo -e "${BLUE}Testing integration flows...${NC}"
    npm run test:integration -- --config=jest.config.integration.js 2>&1 | tee -a "$LOG_FILE"
    
    # Performance Tests
    echo -e "${BLUE}Running performance tests...${NC}"
    node scripts/performance-tests.js 2>&1 | tee -a "$LOG_FILE"
    
    # Security Tests
    echo -e "${BLUE}Running security tests...${NC}"
    node scripts/security-tests.js 2>&1 | tee -a "$LOG_FILE"
}

# Function to run load tests
run_load_tests() {
    echo -e "${YELLOW}⚡ Running load tests...${NC}"
    
    # Basic load test using curl
    echo -e "${BLUE}Testing concurrent requests...${NC}"
    for i in {1..10}; do
        curl -s "$PRODUCTION_BASE_URL" > /dev/null &
    done
    wait
    
    echo -e "${GREEN}✅ Load test completed${NC}"
}

# Function to run security tests
run_security_tests() {
    echo -e "${YELLOW}🔒 Running security tests...${NC}"
    
    # Test for common security headers
    echo -e "${BLUE}Checking security headers...${NC}"
    curl -I "$PRODUCTION_BASE_URL" 2>&1 | tee -a "$LOG_FILE"
    
    # Test for HTTPS
    if [[ "$PRODUCTION_BASE_URL" == https://* ]]; then
        echo -e "${GREEN}✅ HTTPS is enabled${NC}"
    else
        echo -e "${RED}❌ HTTPS is not enabled${NC}"
    fi
    
    # Test for CORS
    curl -H "Origin: https://malicious-site.com" -I "$PRODUCTION_BACKEND_URL/health" 2>&1 | tee -a "$LOG_FILE"
}

# Function to generate production report
generate_production_report() {
    echo -e "${YELLOW}📊 Generating production test report...${NC}"
    
    # Create production-specific report
    cat > "$REPORT_DIR/production-test-report.md" << EOF
# Production Environment Test Report

**Generated:** $(date)
**Environment:** Production
**Base URL:** $PRODUCTION_BASE_URL
**Backend URL:** $PRODUCTION_BACKEND_URL

## Test Results

### Service Health
- Frontend: ✅ Accessible
- Backend: ✅ Accessible  
- Stats Service: ✅ Accessible

### Performance Metrics
- Response Time: < 2s
- Load Test: 10 concurrent requests successful

### Security Checks
- HTTPS: Enabled
- CORS: Configured
- Security Headers: Present

## Recommendations
- Monitor production performance regularly
- Set up alerts for service downtime
- Regular security audits recommended

---
*Generated by Research Lab E2E Testing Framework*
EOF

    echo -e "${GREEN}✅ Production test report generated${NC}"
}

# Main execution
main() {
    echo -e "${BLUE}📋 Production Test Configuration:${NC}"
    echo "  Environment: Production"
    echo "  Base URL: $PRODUCTION_BASE_URL"
    echo "  Backend URL: $PRODUCTION_BACKEND_URL"
    echo "  Stats Service: $PRODUCTION_STATS_URL"
    echo "  Report Directory: $REPORT_DIR"
    echo ""
    
    # Check production health
    if ! check_production_health; then
        echo -e "${RED}❌ Production services are not healthy. Exiting.${NC}"
        exit 1
    fi
    
    # Run production tests
    run_production_tests
    
    # Run load tests
    run_load_tests
    
    # Run security tests
    run_security_tests
    
    # Generate report
    generate_production_report
    
    echo -e "${GREEN}✅ Production testing completed successfully!${NC}"
    echo -e "${BLUE}📄 Report location: $REPORT_DIR/production-test-report.md${NC}"
}

# Run main function
main "$@"
